import React, { useState } from 'react';
import { GitPullRequest, Copy, Check, X, FileCode, Sparkles } from 'lucide-react';
import toast from 'react-hot-toast';

export default function GitPatchModal({ patch, onClose }) {
  const [copied, setCopied] = useState(false);

  if (!patch) return null;

  const handleCopy = () => {
    navigator.clipboard.writeText(patch.diff);
    setCopied(true);
    toast.success('Unified Git diff copied to clipboard');
    setTimeout(() => setCopied(false), 2000);
  };

  const diffLines = (patch.diff || '').split('\n');

  return (
    <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-4">
      <div className="glass-card max-w-3xl w-full max-h-[85vh] flex flex-col border border-primary/30 shadow-2xl overflow-hidden animate-in fade-in zoom-in-95 duration-200">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-white/10 bg-surface/50">
          <div className="flex items-center gap-2.5">
            <div className="w-8 h-8 rounded-lg bg-primary/20 border border-primary/30 flex items-center justify-center text-primary">
              <GitPullRequest size={18} />
            </div>
            <div>
              <h3 className="font-semibold text-text-base text-sm flex items-center gap-2">
                AI Unified Git Patch <Sparkles size={14} className="text-secondary" />
              </h3>
              <p className="text-xs text-muted">Ready-to-apply code patch generated by Claude</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-muted hover:text-text-base hover:bg-white/5 transition-colors"
          >
            <X size={18} />
          </button>
        </div>

        {/* Content Body */}
        <div className="p-6 space-y-4 overflow-y-auto flex-1">
          {/* Explanation */}
          {patch.explanation && (
            <div className="bg-primary/10 border border-primary/20 rounded-xl p-3.5 text-xs text-text-base leading-relaxed">
              <span className="font-semibold text-primary block mb-1">Fix Rationale:</span>
              {patch.explanation}
            </div>
          )}

          {/* Unified Diff View */}
          <div className="rounded-xl border border-white/10 overflow-hidden bg-[#0A0E17]">
            <div className="flex items-center justify-between px-4 py-2 bg-black/40 border-b border-white/5 text-xs text-muted">
              <span className="flex items-center gap-1.5 font-mono">
                <FileCode size={13} /> unified diff (git apply)
              </span>
              <button
                onClick={handleCopy}
                className="flex items-center gap-1 text-[11px] font-semibold text-primary hover:text-primary-hover transition-colors"
              >
                {copied ? <Check size={12} /> : <Copy size={12} />}
                {copied ? 'Copied' : 'Copy Diff'}
              </button>
            </div>

            <div className="p-4 font-mono text-xs overflow-x-auto max-h-96 leading-5">
              {diffLines.map((line, i) => {
                let lineStyle = 'text-muted';
                if (line.startsWith('+') && !line.startsWith('+++')) {
                  lineStyle = 'text-green-400 bg-green-500/10 block px-1 -mx-1 rounded-sm';
                } else if (line.startsWith('-') && !line.startsWith('---')) {
                  lineStyle = 'text-red-400 bg-red-500/10 block px-1 -mx-1 rounded-sm';
                } else if (line.startsWith('@@')) {
                  lineStyle = 'text-secondary font-semibold block pt-1';
                } else if (line.startsWith('---') || line.startsWith('+++')) {
                  lineStyle = 'text-yellow-400 font-semibold';
                }

                return (
                  <div key={i} className={lineStyle}>
                    {line || ' '}
                  </div>
                );
              })}
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 py-3.5 border-t border-white/10 bg-surface/30 flex items-center justify-between">
          <span className="text-xs text-muted font-mono">
            Apply via: <code className="text-text-base bg-black/40 px-1.5 py-0.5 rounded">git apply patch.diff</code>
          </span>
          <div className="flex gap-2">
            <button
              onClick={handleCopy}
              className="btn-primary text-xs px-4 py-1.5 flex items-center gap-1.5"
            >
              {copied ? <Check size={14} /> : <Copy size={14} />} Copy Git Patch
            </button>
            <button
              onClick={onClose}
              className="btn-secondary text-xs px-3 py-1.5"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
